### ISSUE TITLE
PRACTICA #3 INTERFAZ GRAFICA MENU 

### ISSUE THREAD

**Issue by magaly1311** [SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-equipo-m-a-r-topicos-a-p#2]
@RAEL12345 @magaly1311 @Adry117
[PRACTICA 3 MENU PRINCPAL.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-interfaz-grafica-en-visual-studio-menu-equipo-m-a-r-topicos-a-p/files/8250319/PRACTICA.3.MENU.PRINCPAL.pdf)

**Comment by mel-16** [comment]
califico el equipo de Melissa Solano Vasquez tienen una puntuación de 19.04

**Comment by josealfredo79** [comment]
Bien hecho y revisado
